-- MySQL Script generated by MySQL Workbench
-- Fri Apr 27 22:48:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Todo` (
  `id` BIGINT(100) NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` INT NULL COMMENT '0: created\n1: finished\n2: snoozed',
  `type` INT NULL COMMENT '0 normal\n1 timer todo\n2 recur todo',
  `todo_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB PARTITION BY LIST(todo_type) PARTITIONS 2() ;

CREATE INDEX `create` ON `mydb`.`Todo` (`created_time` ASC);

CREATE INDEX `update` ON `mydb`.`Todo` (`updated_time` ASC);

CREATE INDEX `status` ON `mydb`.`Todo` (`status` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `created_time` ON `mydb`.`Project` (`created_time` ASC);

CREATE INDEX `updated_time` ON `mydb`.`Project` (`updated_time` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ProjectTodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectTodo` (
  `todo_id` INT NOT NULL,
  `project_id` VARCHAR(45) NOT NULL,
  `Todo_id` BIGINT(100) NOT NULL,
  `Project_id` INT NOT NULL,
  PRIMARY KEY (`todo_id`, `project_id`, `Todo_id`, `Project_id`),
  CONSTRAINT `fk_ProjectTodo_Todo`
    FOREIGN KEY (`Todo_id`)
    REFERENCES `mydb`.`Todo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectTodo_Project1`
    FOREIGN KEY (`Project_id`)
    REFERENCES `mydb`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ProjectTodo_Todo_idx` ON `mydb`.`ProjectTodo` (`Todo_id` ASC);

CREATE INDEX `fk_ProjectTodo_Project1_idx` ON `mydb`.`ProjectTodo` (`Project_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
